Repository chrisfalla/Backend_La_Brujula_Llanera, pull requests merged in 2025-05, with the labels that each got.

#67 feat: :zap: Adding intuitive Image Categories for home
  src/application/use-cases/GetMoreVisitedPlaces.js
  src/application/use-cases/PromotedPlacesByCategory.js
  src/application/use-cases/PromotedPlacesByTag.js
Labels: enhancement

#68 CategoryNames for Home
  src/application/use-cases/GetMoreVisitedPlaces.js
  src/application/use-cases/PromotedPlacesByCategory.js
  src/application/use-cases/PromotedPlacesByTag.js
Labels: enhancement

#70 Feature/t 069
  server.js
  src/application/DTOs/CategoryDTO.js
  src/application/DTOs/ImageDTO.js
  src/application/DTOs/PlaceDetailDTO.js
  src/application/DTOs/SocialMediaDTO.js
  src/application/use-cases/PlaceDetailUseCase.js
  src/domain/entities/Place.js
  src/domain/entities/SocialMedia.js
  src/domain/entities/SocialMediaByPlace.js
  src/domain/repositories/IImageByPlaceRepository.js
  src/domain/repositories/IImageCategoryRepository.js
  src/domain/repositories/IPlaceRepository.js
  src/domain/repositories/IReviewRepository.js
  src/domain/repositories/ISocialMediaByPlaceRepository.js
  src/infrastructure/models/PlaceModel.js
  src/infrastructure/models/SocialMediaByPlaceModel.js
  src/infrastructure/models/SocialMediaModel.js
  src/infrastructure/repositories/ImageByPlaceRepository.js
  src/infrastructure/repositories/PlaceRepository.js
  src/infrastructure/repositories/ReviewRepository.js
  src/infrastructure/repositories/SocialMediaByPlaceRepository.js
  src/interfaces/controllers/LogVisitedController.js
  src/interfaces/controllers/PlaceDetailsController.js
  src/interfaces/routes/PlaceDetailsRoute.js
Labels: enhancement

#72 Feature/t 071
  .env
  .env example
  .gitignore
  server.js
  src/application/DTOs/CreateUserDTO.js
  src/application/DTOs/LogInDTO.js
  src/application/DTOs/UserDTO.js
  src/application/use-cases/GetUserByIdUseCase.js
  src/application/use-cases/LoginUserUseCase.js
  src/application/use-cases/RegisterUserUseCase.js
  src/application/utils/jwt.js
  src/domain/entities/User.js
  src/domain/repositories/IUserRepository.js
  src/infrastructure/models/UserModel.js
  src/infrastructure/repositories/UserRepository.js
  src/interfaces/controllers/UserController.js
  src/interfaces/middlewares/authMiddleware.js
  src/interfaces/routes/UserRoute.js
Labels: enhancement

#73 Develop
  .env
  .env example
  .gitignore
  server.js
  src/application/DTOs/CategoryDTO.js
  src/application/DTOs/CreateUserDTO.js
  src/application/DTOs/ImageDTO.js
  src/application/DTOs/LogInDTO.js
  src/application/DTOs/PlaceDetailDTO.js
  src/application/DTOs/SocialMediaDTO.js
  src/application/DTOs/UserDTO.js
  src/application/use-cases/GetUserByIdUseCase.js
  src/application/use-cases/LoginUserUseCase.js
  src/application/use-cases/PlaceDetailUseCase.js
  src/application/use-cases/RegisterUserUseCase.js
  src/application/utils/jwt.js
  src/domain/entities/Place.js
  src/domain/entities/SocialMedia.js
  src/domain/entities/SocialMediaByPlace.js
  src/domain/entities/User.js
  src/domain/repositories/IImageByPlaceRepository.js
  src/domain/repositories/IImageCategoryRepository.js
  src/domain/repositories/IPlaceRepository.js
  src/domain/repositories/IReviewRepository.js
  src/domain/repositories/ISocialMediaByPlaceRepository.js
  src/domain/repositories/IUserRepository.js
  src/infrastructure/models/PlaceModel.js
  src/infrastructure/models/SocialMediaByPlaceModel.js
  src/infrastructure/models/SocialMediaModel.js
  src/infrastructure/models/UserModel.js
  src/infrastructure/repositories/ImageByPlaceRepository.js
  src/infrastructure/repositories/PlaceRepository.js
  src/infrastructure/repositories/ReviewRepository.js
  src/infrastructure/repositories/SocialMediaByPlaceRepository.js
  src/infrastructure/repositories/UserRepository.js
  src/interfaces/controllers/PlaceDetailsController.js
  src/interfaces/controllers/UserController.js
  src/interfaces/middlewares/authMiddleware.js
  src/interfaces/routes/PlaceDetailsRoute.js
  src/interfaces/routes/UserRoute.js
Labels: enhancement

#75 Feature/t 074
  .env
  .env example
  .gitignore
  src/interfaces/controllers/HomeController.js
  src/interfaces/routes/HomeRoute.js
Labels: bug

#77 BugFix PromotedPlacesByTag Endpoint put GET instead of POST method into Develop
  src/interfaces/controllers/HomeController.js
  src/interfaces/routes/HomeRoute.js
Labels: bug

#78 Feature/t 077
  src/application/use-cases/PlaceDetailUseCase.js
Labels: enhancement

#80 Feature/T-076
  server.js
  src/application/DTOs/CreateUserDTO.js
  src/application/DTOs/PlaceDetailDTO.js
  src/application/DTOs/UserDetailDTO.js
  src/application/use-cases/ForgotPasswordUseCase.js
  src/application/use-cases/PlaceDetailUseCase.js
  src/domain/repositories/IUserRepository.js
  src/infrastructure/repositories/UserRepository.js
  src/interfaces/controllers/PlaceDetailsController.js
  src/interfaces/controllers/UserController.js
  src/interfaces/routes/UserRoute.js
Labels: enhancement

#81 UserDto into Main
  server.js
  src/application/DTOs/CreateUserDTO.js
  src/application/DTOs/PlaceDetailDTO.js
  src/application/DTOs/UserDetailDTO.js
  src/application/use-cases/ForgotPasswordUseCase.js
  src/application/use-cases/PlaceDetailUseCase.js
  src/domain/repositories/IUserRepository.js
  src/infrastructure/repositories/UserRepository.js
  src/interfaces/controllers/PlaceDetailsController.js
  src/interfaces/controllers/UserController.js
  src/interfaces/routes/UserRoute.js
Labels: enhancement

#82 feat: :zap: Adding User Object for User
  server.js
  src/application/use-cases/GetUserUseCase.js
  src/infrastructure/repositories/UserRepository.js
  src/interfaces/controllers/UserController.js
Labels: enhancement

#84 Feature/t 059
  server.js
  src/application/use-cases/GetFavoritePlacesByUserUseCase.js
  src/application/use-cases/PromotedPlacesByTag.js
  src/domain/repositories/IFavoriteRepository.js
  src/infrastructure/repositories/FavoriteRepository.js
  src/interfaces/controllers/FavoriteController.js
  src/interfaces/routes/FavoriteRoute.js
Labels: enhancement

#85 GetFavoritesByUser into Main
  server.js
  src/application/use-cases/GetFavoritePlacesByUserUseCase.js
  src/application/use-cases/PromotedPlacesByTag.js
  src/domain/repositories/IFavoriteRepository.js
  src/infrastructure/repositories/FavoriteRepository.js
  src/interfaces/controllers/FavoriteController.js
  src/interfaces/routes/FavoriteRoute.js
Labels: enhancement

#88 Feature/T-087
  server.js
  src/application/use-cases/GetReviewsByPlaceUseCase.js
  src/domain/repositories/IReviewRepository.js
  src/domain/repositories/IUserRepository.js
  src/infrastructure/repositories/ReviewRepository.js
  src/interfaces/controllers/ReviewController.js
  src/interfaces/routes/ReviewRoute.js
Labels: enhancement

#89 ViewReviewsByPlace EndPoint into Develop
  server.js
  src/application/use-cases/GetReviewsByPlaceUseCase.js
  src/domain/repositories/IReviewRepository.js
  src/domain/repositories/IUserRepository.js
  src/infrastructure/repositories/ReviewRepository.js
  src/interfaces/controllers/ReviewController.js
  src/interfaces/routes/ReviewRoute.js
Labels: enhancement

#92 T-090 Create Endpoint for Termns and Conditions
  server.js
  src/interfaces/controllers/TermsAndConditionsController.js
  src/interfaces/routes/TermsAndConditionsRoute.js
Labels: enhancement, deploy

#94 Feature/T-091
  .env
  package-lock.json
  package.json
  server.js
  src/application/DTOs/UserDTO.js
  src/application/use-cases/PasswordRecoveryUseCase.js
  src/domain/repositories/IEmailRepository.js
  src/domain/repositories/IPasswordRecoveryRepository.js
  src/infrastructure/models/PasswordRecoveryModel.js
  src/infrastructure/repositories/EmailRepository.js
  src/infrastructure/repositories/PasswordRecoveryRepository.js
  src/infrastructure/repositories/UserRepository.js
  src/interfaces/controllers/PasswordRecoveryController.js
  src/interfaces/routes/HomeRoute.js
  src/interfaces/routes/PasswordRecoveryRoute.js
Labels: enhancement

#95 Forgot Password into Main
  .env
  package-lock.json
  package.json
  server.js
  src/application/DTOs/UserDTO.js
  src/application/use-cases/PasswordRecoveryUseCase.js
  src/domain/repositories/IEmailRepository.js
  src/domain/repositories/IPasswordRecoveryRepository.js
  src/infrastructure/models/PasswordRecoveryModel.js
  src/infrastructure/repositories/EmailRepository.js
  src/infrastructure/repositories/PasswordRecoveryRepository.js
  src/infrastructure/repositories/UserRepository.js
  src/interfaces/controllers/PasswordRecoveryController.js
  src/interfaces/routes/HomeRoute.js
  src/interfaces/routes/PasswordRecoveryRoute.js
Labels: enhancement

#97 Feature/T-096
  src/application/use-cases/PasswordRecoveryUseCase.js
Labels: enhancement

#98 Forgot Password into Main
  src/application/use-cases/PasswordRecoveryUseCase.js
Labels: enhancement

#101 Feature/T-096
  src/application/use-cases/ValidateCodeUseCase.js
  src/infrastructure/repositories/PasswordRecoveryRepository.js
Labels: enhancement

#102 Develop
  src/application/use-cases/ValidateCodeUseCase.js
  src/infrastructure/repositories/PasswordRecoveryRepository.js
Labels: enhancement

#106 Feature/T-086
  server.js
  src/application/use-cases/AddCommentUseCase.js
  src/domain/repositories/IReviewRepository.js
  src/infrastructure/repositories/ReviewRepository.js
  src/interfaces/controllers/ReviewController.js
  src/interfaces/routes/ReviewRoute.js
Labels: enhancement

#107 AddComment into Main
  server.js
  src/application/use-cases/AddCommentUseCase.js
  src/domain/repositories/IReviewRepository.js
  src/infrastructure/repositories/ReviewRepository.js
  src/interfaces/controllers/ReviewController.js
  src/interfaces/routes/ReviewRoute.js
Labels: enhancement

#109 Feature/T-103
  server.js
  src/application/use-cases/UpdateUserInfoUseCase.js
  src/domain/repositories/IUserRepository.js
  src/infrastructure/repositories/UserRepository.js
  src/interfaces/controllers/UserController.js
  src/interfaces/routes/UserRoute.js
Labels: enhancement

#110 UpdateUserInfo into Main
  server.js
  src/application/use-cases/UpdateUserInfoUseCase.js
  src/domain/repositories/IUserRepository.js
  src/infrastructure/repositories/UserRepository.js
  src/interfaces/controllers/UserController.js
  src/interfaces/routes/UserRoute.js
Labels: enhancement

#111 feat: :zap: Adding post Log for Log table
  server.js
  src/application/DTOs/AddLogDTO.js
  src/application/use-cases/AddLogUseCase.js
  src/domain/repositories/ILogVisitRepository.js
  src/infrastructure/models/LogVisitModel.js
  src/infrastructure/repositories/LogVisitedRepository.js
  src/interfaces/controllers/LogVisitedController.js
  src/interfaces/routes/LogRoute.js
Labels: enhancement

#112 Develop
  server.js
  src/application/DTOs/AddLogDTO.js
  src/application/use-cases/AddLogUseCase.js
  src/domain/repositories/ILogVisitRepository.js
  src/infrastructure/models/LogVisitModel.js
  src/infrastructure/repositories/LogVisitedRepository.js
  src/interfaces/controllers/LogVisitedController.js
  src/interfaces/routes/LogRoute.js
Labels: enhancement

#118 feat: :zap: Adding PlacesByCategoryEndpoint into placeDetails
  server.js
  src/application/DTOs/PlaceByCategoryDTO.js
  src/application/use-cases/GetPlacesByCategoryUseCase.js
  src/interfaces/controllers/PlaceDetailsController.js
  src/interfaces/routes/PlaceDetailsRoute.js
Labels: enhancement
