Repository chrisfalla/Backend_La_Brujula_Llanera, pull requests merged in 2025-04, with the labels that each got.

#23 Feature/t 016
  .env
  README.md
  dependencesAndComands.txt
  nodemon.json
  server.js
  src/controllers/CategoryController.js
  src/database/testConnection.js
  src/models/Categorie.js
  src/models/index.js
  src/routes/AuthRoute.js
  src/routes/CategoryRoute.js
  src/services/CategoryService.js
  src/services/exampleService.js
  swagger/swaggerConfig.js
  testConnection.js
  tests/testConnection.js
  tests/testSupabaseConnection.js
Labels: enhancement

#33 T-015 Create Categories Endpoint
  server.js
  src/controllers/CategoryController.js
  src/models/Categorie.js
  src/routes/CategoryRoute.js
  src/services/CategoryService.js
Labels: enhancement

#44 Feature/T 034 Database Restructuring
  data-seeders.xlsx
  package-lock.json
  package.json
  src/database/generate-data-seeders.xlsx.js
  src/database/migrations/020250318212222-create-user.js
  src/database/migrations/120250318211748-create-category.js
  src/database/migrations/20250413000001-create-dbo.Categorie.js
  src/database/migrations/20250413000002-create-dbo.Tag.js
  src/database/migrations/20250413000003-create-dbo.Role.js
  src/database/migrations/20250413000004-create-dbo.User.js
  src/database/migrations/20250413000005-create-dbo.Address.js
  src/database/migrations/20250413000006-create-dbo.DeviceInfo.js
  src/database/migrations/20250413000007-dbo.ImageCategorie.js
  src/database/migrations/20250413000008-create-dbo.Place.js
  src/database/migrations/20250413000009-create-dbo.AddressByPlace.js
  src/database/migrations/20250413000010-create-dbo.TagByPlace.js
  src/database/migrations/20250413000011-create-dbo.Review.js
  src/database/migrations/20250413000012-dbo.LogVist.js
  src/database/migrations/20250413000013-create-dbo.ImageByPlace.js
  src/database/migrations/220250318211851-create-place.js
  src/database/migrations/320250318212034-create-comentary.js
  src/database/migrations/420250318212052-create-images.js
  src/database/migrations/520250318212203-create-best-selling-product.js
  src/database/migrations/620250318212121-create-category-image.js
  src/database/seeders/20250413000001-seed-categorie.js
  src/database/seeders/20250413000002-seed-tag.js
  src/database/seeders/20250413000003-seed-role.js
  src/database/seeders/20250413000004-seed-user.js
  src/database/seeders/20250413000005-seed-address.js
  src/database/seeders/20250413000006-seed-deviceinfo.js
  src/database/seeders/20250413000007-seed-imagecategorie.js
  src/database/seeders/20250413000008-seed-place.js
  src/database/seeders/20250413000009-seed-addressbyplace.js
  src/database/seeders/20250413000010-seed-tagbyplace.js
  src/database/seeders/20250413000011-seed-review.js
  src/database/seeders/20250413000012-seed-logvisit.js
  src/database/seeders/20250413000013-seed-imagebyplace.js
  src/database/seeders/img/1.webp
  src/database/seeders/img/2.webp
  src/database/seeders/img/3.webp
  src/database/seeders/img/4.webp
  src/database/seeders/img/5.webp
  src/database/seeders/img/6.webp
  src/database/seeders/img/7.webp
  src/database/seeders/img/8.webp
  src/database/seeders/seeder-bestSellingProduct.js
  src/database/seeders/seeder-category.js
  src/database/seeders/seeder-category_image.js
  src/database/seeders/seeder-comentary.js
  src/database/seeders/seeder-images.js
  src/database/seeders/seeder-place.js
  src/database/seeders/seeder-user.js
  tests/checkTables.js
Labels: duplicate, enhancement

#46 feat: :zap: I've implemented hybrid architecture structure to the project
  package-lock.json
  package.json
  server.js
  src/infrastructure/database/generate-data-seeders.xlsx.js
  src/infrastructure/database/migrations/20250413000001-create-dbo.Categorie.js
  src/infrastructure/database/migrations/20250413000002-create-dbo.Tag.js
  src/infrastructure/database/migrations/20250413000003-create-dbo.Role.js
  src/infrastructure/database/migrations/20250413000004-create-dbo.User.js
  src/infrastructure/database/migrations/20250413000005-create-dbo.Address.js
  src/infrastructure/database/migrations/20250413000006-create-dbo.DeviceInfo.js
  src/infrastructure/database/migrations/20250413000007-dbo.ImageCategorie.js
  src/infrastructure/database/migrations/20250413000008-create-dbo.Place.js
  src/infrastructure/database/migrations/20250413000009-create-dbo.AddressByPlace.js
  src/infrastructure/database/migrations/20250413000010-create-dbo.TagByPlace.js
  src/infrastructure/database/migrations/20250413000011-create-dbo.Review.js
  src/infrastructure/database/migrations/20250413000012-dbo.LogVist.js
  src/infrastructure/database/migrations/20250413000013-create-dbo.ImageByPlace.js
  src/infrastructure/database/seeders/20250413000001-seed-categorie.js
  src/infrastructure/database/seeders/20250413000002-seed-tag.js
  src/infrastructure/database/seeders/20250413000003-seed-role.js
  src/infrastructure/database/seeders/20250413000004-seed-user.js
  src/infrastructure/database/seeders/20250413000005-seed-address.js
  src/infrastructure/database/seeders/20250413000006-seed-deviceinfo.js
  src/infrastructure/database/seeders/20250413000007-seed-imagecategorie.js
  src/infrastructure/database/seeders/20250413000008-seed-place.js
  src/infrastructure/database/seeders/20250413000009-seed-addressbyplace.js
  src/infrastructure/database/seeders/20250413000010-seed-tagbyplace.js
  src/infrastructure/database/seeders/20250413000011-seed-review.js
  src/infrastructure/database/seeders/20250413000012-seed-logvisit.js
  src/infrastructure/database/seeders/20250413000013-seed-imagebyplace.js
  src/infrastructure/models/Categorie.js
  src/infrastructure/models/index.js
  src/infrastructure/models/user.js
  src/infrastructure/repositories/CategoryService.js
  src/interfaces/controllers/CategoryController.js
  src/interfaces/docs/swagger/swaggerConfig.js
  src/interfaces/middlewares/exampleMiddleware.js
  src/interfaces/routes/AuthRoute.js
  src/interfaces/routes/CategoryRoute.js
  src/interfaces/routes/UserRoute.js
  src/interfaces/routes/postsRoute.js
Labels: enhancement

#47 Feature/T-034 Add Table Favorites o DB
  src/infrastructure/database/generate-data-seeders.xlsx.js
  src/infrastructure/database/migrations/20250416000001-create-dbo.Favorites.js
  src/infrastructure/database/seeders/20250416000014-seed-favorites.js
Labels: enhancement

#48 Feature/t 038
  .env
  server.js
  src/application/use-cases/CategoryUseCase.js
  src/domain/entities/Category.js
  src/domain/repositories/ICategoryRepository.js
  src/infrastructure/database/sequelize.js
  src/infrastructure/models/Categorie.js
  src/infrastructure/models/CategoryModel.js
  src/infrastructure/models/index.js
  src/infrastructure/models/user.js
  src/infrastructure/repositories/CategoryRepository.js
  src/infrastructure/repositories/CategoryService.js
  src/interfaces/controllers/CategoryController.js
  src/interfaces/docs/swagger/swaggerConfig.js
  src/interfaces/routes/AuthRoute.js
  src/interfaces/routes/CategoryRoute.js
  src/interfaces/routes/UserRoute.js
  src/interfaces/routes/postsRoute.js
Labels: enhancement

#50 feat: :zap: I implemented Tags Endpoint and its swagger documentation
  server.js
  src/application/TagUseCase.js
  src/domain/entities/Tag.js
  src/domain/repositories/ITagRepostory.js
  src/infrastructure/models/TagModel.js
  src/infrastructure/models/index.js
  src/infrastructure/repositories/TagRepository.js
  src/interfaces/controllers/CategoryController.js
  src/interfaces/controllers/TagController.js
  src/interfaces/routes/TagRoute.js
Labels: enhancement

#54 Feature/T- 053
  SECURITY.md
  src/application/DTOs/CategoryDTO.js
  src/application/DTOs/MoreVisitedPlacesDTO.js
  src/application/DTOs/RatingStarsByCategory.js
  src/application/DTOs/RatingStarsByTagsDTO.js
  src/application/DTOs/TagDTO.js
  src/application/use-cases/CategoryUseCase.js
  src/application/use-cases/GetMoreVisitedPlaces.js
  src/application/use-cases/GetTopRatedPlacesByCategory.js
  src/application/use-cases/GetTopRatedPlacesByTags.js
  src/application/use-cases/TagUseCase.js
  src/domain/entities/Address.js
  src/domain/entities/AddressByPlace.js
  src/domain/entities/Category.js
  src/domain/repositories/IAddressByPlace.js
  src/domain/repositories/IAddressRepository.js
  src/domain/repositories/ITagRepostory.js
  src/infrastructure/models/AddressByPlaceModel.js
  src/infrastructure/models/AddressModel.js
  src/infrastructure/models/CategoryModel.js
  src/infrastructure/repositories/AddressByPlaceRepository.js
  src/infrastructure/repositories/AddressRepository.js
  src/infrastructure/repositories/TagRepository.js
Labels: enhancement

#56 feat: :zap: Adding Favorite EndPoint
  server.js
  src/application/use-cases/FavoriteUseCase.js
  src/domain/entities/Favorite.js
  src/domain/repositories/IFavoriteRepository.js
  src/infrastructure/models/FavoriteModel.js
  src/infrastructure/repositories/FavoriteRepository.js
  src/interfaces/controllers/FavoriteController.js
  src/interfaces/routes/FavoriteRoute.js
Labels: enhancement

#62 Feature/T-058
  server.js
  src/application/DTOs/CategoryDTO.js
  src/application/DTOs/MoreVisitedPlacesDTO.js
  src/application/DTOs/RatingStarsByCategory.js
  src/application/DTOs/RatingStarsByTagsDTO.js
  src/application/DTOs/TagDTO.js
  src/application/use-cases/CategoryUseCase.js
  src/application/use-cases/GetMoreVisitedPlaces.js
  src/application/use-cases/GetTopRatedPlacesByCategory.js
  src/application/use-cases/GetTopRatedPlacesByTags.js
  src/application/use-cases/TagUseCase.js
  src/domain/entities/Address.js
  src/domain/entities/AddressByPlace.js
  src/domain/entities/Category.js
  src/domain/entities/ImageByPlace.js
  src/domain/entities/ImageCategory.js
  src/domain/entities/LogVisitRepository.js
  src/domain/entities/Place.js
  src/domain/entities/Review.js
  src/domain/entities/Tag.js
  src/domain/entities/TagByPlace.js
  src/domain/repositories/IAddressByPlace.js
  src/domain/repositories/IAddressRepository.js
  src/domain/repositories/ICategoryRepository.js
  src/domain/repositories/IImageByPlaceRepository.js
  src/domain/repositories/IImageCategoryRepository.js
  src/domain/repositories/ILogVisitRepository.js
  src/domain/repositories/IPlaceRepository.js
  src/domain/repositories/IReviewRepository.js
  src/domain/repositories/ITagByPlaceRepository.js
  src/domain/repositories/ITagRepostory.js
  src/infrastructure/models/AddressByPlaceModel.js
  src/infrastructure/models/AddressModel.js
  src/infrastructure/models/CategoryModel.js
  src/infrastructure/models/ImageByPlaceModel.js
  src/infrastructure/models/ImageCategoryModel.js
  src/infrastructure/models/LogVisitModel.js
  src/infrastructure/models/PlaceModel.js
  src/infrastructure/models/ReviewModel.js
  src/infrastructure/models/TagByPlaceModel.js
  src/infrastructure/models/TagModel.js
  src/infrastructure/repositories/AddressByPlaceRepository.js
  src/infrastructure/repositories/AddressRepository.js
  src/infrastructure/repositories/CategoryRepository.js
  src/infrastructure/repositories/ImageByPlaceRepository.js
  src/infrastructure/repositories/ImageCategoryRepository.js
  src/infrastructure/repositories/LogVisitedRepository.js
  src/infrastructure/repositories/PlaceRepository.js
  src/infrastructure/repositories/ReviewRepository.js
  src/infrastructure/repositories/TagByPlaceRepository.js
  src/infrastructure/repositories/TagRepository.js
  src/interfaces/controllers/CategoryController.js
  src/interfaces/controllers/LogVisitedController.js
  src/interfaces/controllers/PlaceController.js
  src/interfaces/controllers/TagController.js
  src/interfaces/routes/CategoryRoute.js
  src/interfaces/routes/HomeRoute.js
  src/interfaces/routes/PlaceRoute.js
  src/interfaces/routes/TagRoute.js
Labels: bug, enhancement

#64 Feature/T-057
  server.js
  src/application/DTOs/MoreVisitedPlacesDTO.js
  src/application/DTOs/PromotedPlacesByCategoryDTO.js
  src/application/DTOs/PromotedPlacesByTagDTO.js
  src/application/use-cases/PromotedPlacesByCategory.js
  src/application/use-cases/PromotedPlacesByTag.js
  src/domain/repositories/ITagByPlaceRepository.js
  src/infrastructure/repositories/TagByPlaceRepository.js
  src/interfaces/controllers/HomeController.js
  src/interfaces/routes/HomeRoute.js
Labels: bug

#65 T-057 Fix Home Endpoint
  server.js
  src/application/DTOs/MoreVisitedPlacesDTO.js
  src/application/DTOs/PromotedPlacesByCategoryDTO.js
  src/application/DTOs/PromotedPlacesByTagDTO.js
  src/application/use-cases/PromotedPlacesByCategory.js
  src/application/use-cases/PromotedPlacesByTag.js
  src/domain/repositories/ITagByPlaceRepository.js
  src/infrastructure/repositories/TagByPlaceRepository.js
  src/interfaces/controllers/HomeController.js
  src/interfaces/routes/HomeRoute.js
Labels: bug
